export interface Material {
  id: string;
  name: string;
  enDesignation: string;
  aisiDesignation: string;
  type: "steel" | "cast-iron" | "non-ferrous";
  uts: string;
  ys: string;
  hardness: string;
  elasticity: string;
  machinability: "Excellent" | "Good" | "Fair" | "Poor";
  heatTreatment: string[];
  gearApplications: string;
  notes: string;
  poisson: string;
  density: string;
}

export const MATERIALS: Material[] = [
  {
    id: "mild-steel",
    name: "Mild Steel",
    enDesignation: "EN1A / 220M07",
    aisiDesignation: "1018 / 12L14",
    type: "steel",
    uts: "420 MPa",
    ys: "350 MPa",
    hardness: "HB 120",
    elasticity: "200 GPa",
    machinability: "Excellent",
    heatTreatment: ["None (standard)", "Case harden (surface)", "Bright drawn — no heat treatment needed"],
    gearApplications: "Light duty, slow speed gears and racks, prototype components, jig and fixture gears",
    notes: "Free-cutting grade. Low carbon content limits strength. Good for low-stress, high-volume machining.",
    poisson: "0.29",
    density: "7.85 g/cm³",
  },
  {
    id: "en8",
    name: "EN8",
    enDesignation: "EN8 / 080M40",
    aisiDesignation: "1040",
    type: "steel",
    uts: "620–850 MPa (HT)",
    ys: "460–690 MPa",
    hardness: "HB 179–229 (HT)",
    elasticity: "200 GPa",
    machinability: "Good",
    heatTreatment: ["Normalise & Temper (N&T)", "Harden & Temper (H&T)", "Induction harden (surface 55–60 HRc)", "No carburising"],
    gearApplications: "Medium duty gears, shafts, couplings, general engineering. Good balance of strength and machinability.",
    notes: "Medium carbon steel. Most widely used engineering steel in the UK. Responds well to induction hardening.",
    poisson: "0.29",
    density: "7.85 g/cm³",
  },
  {
    id: "en9",
    name: "EN9",
    enDesignation: "EN9 / 070M55",
    aisiDesignation: "1055",
    type: "steel",
    uts: "700–900 MPa (HT)",
    ys: "530–740 MPa",
    hardness: "HB 201–255 (HT)",
    elasticity: "200 GPa",
    machinability: "Good",
    heatTreatment: ["Normalise & Temper", "Harden & Temper", "Induction harden (surface 58–62 HRc)"],
    gearApplications: "Medium to high duty gears, cams, crankshafts, spring-loaded components",
    notes: "Higher carbon than EN8, giving better wear resistance. More prone to distortion on quenching than alloy steels.",
    poisson: "0.29",
    density: "7.85 g/cm³",
  },
  {
    id: "en19",
    name: "EN19 (4140)",
    enDesignation: "EN19 / 709M40",
    aisiDesignation: "4140 / 4142",
    type: "steel",
    uts: "850–1000 MPa (HT)",
    ys: "700–860 MPa",
    hardness: "HB 248–302 (HT)",
    elasticity: "200 GPa",
    machinability: "Good",
    heatTreatment: ["Through harden & temper", "Normalise & Temper", "Nitriding (58–62 HRc case)", "Induction harden"],
    gearApplications: "High duty gears, pinions, shafts, axles. Widely used in machine tool and automotive industries.",
    notes: "Cr-Mo alloy steel. Excellent combination of strength, toughness, and machinability. Good hardenability.",
    poisson: "0.28",
    density: "7.85 g/cm³",
  },
  {
    id: "en24",
    name: "EN24 (4340)",
    enDesignation: "EN24 / 817M40",
    aisiDesignation: "4340",
    type: "steel",
    uts: "1000–1150 MPa (HT)",
    ys: "850–1000 MPa",
    hardness: "HB 302–363 (HT)",
    elasticity: "200 GPa",
    machinability: "Fair",
    heatTreatment: ["Through harden & temper", "Case carburise (58–63 HRc)", "Nitriding", "Induction harden"],
    gearApplications: "High performance gears, aerospace gearing, heavy-duty transmissions, shafts requiring high fatigue strength",
    notes: "Ni-Cr-Mo alloy steel. Superior toughness vs EN19. Excellent hardenability — can be through-hardened in large sections.",
    poisson: "0.28",
    density: "7.85 g/cm³",
  },
  {
    id: "en31",
    name: "EN31 (52100)",
    enDesignation: "EN31 / 535A99",
    aisiDesignation: "52100",
    type: "steel",
    uts: "620–1000 MPa",
    ys: "420–840 MPa",
    hardness: "HB 207 (annealed); 60–64 HRc (hardened)",
    elasticity: "200 GPa",
    machinability: "Fair",
    heatTreatment: ["Through harden (oil quench) → 60–64 HRc", "Anneal for machining", "Grind after hardening — must temper 150–160°C"],
    gearApplications: "High precision gears (form ground after hardening), bearing races, roller bearings, precision tooling",
    notes: "High carbon, high chromium steel. Bearing-quality steel. Very hard when hardened but brittle — primarily used where extreme wear resistance is needed.",
    poisson: "0.28",
    density: "7.81 g/cm³",
  },
  {
    id: "grey-cast-iron",
    name: "Grey Cast Iron",
    enDesignation: "Grade 250 / BS1452",
    aisiDesignation: "Class 35 (ASTM A48)",
    type: "cast-iron",
    uts: "250 MPa",
    ys: "N/A (brittle)",
    hardness: "HB 180–240",
    elasticity: "100 GPa",
    machinability: "Excellent",
    heatTreatment: ["Stress relief anneal (550°C, 1h)", "Not normally through-hardened"],
    gearApplications: "Large gear blanks, gear housings, slow-speed large gears, worm gear housings. Excellent vibration damping.",
    notes: "Good in compression, poor in tension. Excellent machinability and vibration damping. Low cost for large castings.",
    poisson: "0.26",
    density: "7.20 g/cm³",
  },
  {
    id: "phosphor-bronze",
    name: "Phosphor Bronze",
    enDesignation: "PB1 / BS1400",
    aisiDesignation: "C51000 / C54400",
    type: "non-ferrous",
    uts: "310–420 MPa",
    ys: "130–380 MPa",
    hardness: "HB 65–120",
    elasticity: "120 GPa",
    machinability: "Excellent",
    heatTreatment: ["None standard", "Solution anneal if cold worked"],
    gearApplications: "Worm wheels (pairs with hardened steel worm), bearings, bushings, slow-speed gears requiring corrosion resistance",
    notes: "Cu-Sn-P alloy. Low coefficient of friction against steel. Excellent choice for worm wheels — conformable and good thermal conductivity.",
    poisson: "0.34",
    density: "8.86 g/cm³",
  },
  {
    id: "aluminium-bronze",
    name: "Aluminium Bronze",
    enDesignation: "AB1 / BS1400",
    aisiDesignation: "C95400",
    type: "non-ferrous",
    uts: "500–620 MPa",
    ys: "195–310 MPa",
    hardness: "HB 140–180",
    elasticity: "120 GPa",
    machinability: "Good",
    heatTreatment: ["Age harden", "Anneal"],
    gearApplications: "Marine worm wheels, high-load bronze gears, hydraulic components, propellers",
    notes: "Cu-Al alloy. Higher strength than phosphor bronze. Good corrosion resistance in seawater. Good alternative for heavily loaded worm wheels.",
    poisson: "0.32",
    density: "7.60 g/cm³",
  },
  {
    id: "brass",
    name: "Brass",
    enDesignation: "CZ121 / CW614N",
    aisiDesignation: "C38500 (free-cutting brass)",
    type: "non-ferrous",
    uts: "350–420 MPa",
    ys: "280–350 MPa",
    hardness: "HB 80–130",
    elasticity: "97 GPa",
    machinability: "Excellent",
    heatTreatment: ["Anneal (stress relief)"],
    gearApplications: "Light duty gears, clock and instrument gears, decorative gears, low-load high-speed gears",
    notes: "Cu-Zn alloy. Free-cutting grades offer best machinability of any metal. Not suitable for high-load applications.",
    poisson: "0.34",
    density: "8.50 g/cm³",
  },
  {
    id: "aluminium-6061",
    name: "Aluminium Alloy 6061-T6",
    enDesignation: "HE20 / BS1474",
    aisiDesignation: "6061-T6",
    type: "non-ferrous",
    uts: "310 MPa",
    ys: "275 MPa",
    hardness: "HB 95",
    elasticity: "69 GPa",
    machinability: "Excellent",
    heatTreatment: ["T6: Solution treat + artificial age", "Anodise for wear resistance"],
    gearApplications: "Aerospace gears (light weight priority), racing, low-load high-speed gears, hand tools",
    notes: "Light weight (2.70 g/cm³). Good strength-to-weight ratio. Anodising improves surface hardness. Not suitable for heavily loaded or abrasive applications.",
    poisson: "0.33",
    density: "2.70 g/cm³",
  },
  {
    id: "stainless-304",
    name: "Stainless Steel 304",
    enDesignation: "A2 / 1.4301",
    aisiDesignation: "304 / 18-8",
    type: "steel",
    uts: "515–620 MPa",
    ys: "205–310 MPa",
    hardness: "HB 215 max",
    elasticity: "193 GPa",
    machinability: "Fair",
    heatTreatment: ["Solution anneal only (cannot through-harden — austenitic)", "No response to conventional hardening"],
    gearApplications: "Corrosion-resistant gears for food processing, pharmaceutical, marine, and chemical plant applications",
    notes: "Austenitic stainless. Work hardens during machining — use sharp tools and flood coolant. Cannot be conventionally hardened. 316 grade for stronger corrosion resistance.",
    poisson: "0.29",
    density: "7.93 g/cm³",
  },
];

export const STANDARD_MODULES = [
  { module: 0.5, dp: 50.8 },
  { module: 0.8, dp: 31.75 },
  { module: 1.0, dp: 25.4 },
  { module: 1.25, dp: 20.32 },
  { module: 1.5, dp: 16.93 },
  { module: 2.0, dp: 12.7 },
  { module: 2.5, dp: 10.16 },
  { module: 3.0, dp: 8.47 },
  { module: 4.0, dp: 6.35 },
  { module: 5.0, dp: 5.08 },
  { module: 6.0, dp: 4.23 },
  { module: 8.0, dp: 3.175 },
  { module: 10.0, dp: 2.54 },
  { module: 12.0, dp: 2.117 },
  { module: 16.0, dp: 1.5875 },
  { module: 20.0, dp: 1.27 },
];

export const INVOLUTE_TABLE = [
  { angle: 10, inv: Math.tan(10 * Math.PI / 180) - 10 * Math.PI / 180 },
  { angle: 12, inv: Math.tan(12 * Math.PI / 180) - 12 * Math.PI / 180 },
  { angle: 14.5, inv: Math.tan(14.5 * Math.PI / 180) - 14.5 * Math.PI / 180 },
  { angle: 15, inv: Math.tan(15 * Math.PI / 180) - 15 * Math.PI / 180 },
  { angle: 17.5, inv: Math.tan(17.5 * Math.PI / 180) - 17.5 * Math.PI / 180 },
  { angle: 20, inv: Math.tan(20 * Math.PI / 180) - 20 * Math.PI / 180 },
  { angle: 22.5, inv: Math.tan(22.5 * Math.PI / 180) - 22.5 * Math.PI / 180 },
  { angle: 25, inv: Math.tan(25 * Math.PI / 180) - 25 * Math.PI / 180 },
  { angle: 27.5, inv: Math.tan(27.5 * Math.PI / 180) - 27.5 * Math.PI / 180 },
  { angle: 30, inv: Math.tan(30 * Math.PI / 180) - 30 * Math.PI / 180 },
];

export const LEWIS_FACTORS: { teeth: number; y_20deg: number; y_14_5deg: number }[] = [
  { teeth: 12, y_20deg: 0.245, y_14_5deg: 0.197 },
  { teeth: 14, y_20deg: 0.276, y_14_5deg: 0.221 },
  { teeth: 17, y_20deg: 0.303, y_14_5deg: 0.243 },
  { teeth: 20, y_20deg: 0.320, y_14_5deg: 0.257 },
  { teeth: 24, y_20deg: 0.337, y_14_5deg: 0.270 },
  { teeth: 30, y_20deg: 0.359, y_14_5deg: 0.286 },
  { teeth: 38, y_20deg: 0.378, y_14_5deg: 0.302 },
  { teeth: 50, y_20deg: 0.408, y_14_5deg: 0.327 },
  { teeth: 60, y_20deg: 0.421, y_14_5deg: 0.339 },
  { teeth: 75, y_20deg: 0.434, y_14_5deg: 0.349 },
  { teeth: 100, y_20deg: 0.446, y_14_5deg: 0.358 },
  { teeth: 150, y_20deg: 0.460, y_14_5deg: 0.371 },
  { teeth: 300, y_20deg: 0.472, y_14_5deg: 0.390 },
  { teeth: 400, y_20deg: 0.480, y_14_5deg: 0.397 },
];
